app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import LoginManager
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))




class Pitches(db.Model):
    '''
    Pitch class to define Pitch Objects
    '''
    __tablename__ = 'pitches'

    id = db.Column(db.Integer,primary_key = True)
    category = db.Column(db.String(225))
    author = db.Column(db.String(225))
    pitch = db.Column(db.String())

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitch(cls,category):
        pitch = Pitches.query.filter_by(category=category).all()
        return pitch

    def __init__(self,category,author,pitch):
        self.category = category
        self.author = author
        self.pitch = pitch

class Feedback(db.Model):
    __tablename__='feedback'

    id = db.Column(db.Integer,primary_key = True)
    author = db.Column(db.String(225))
    feedback = db.Column(db.String())

    def save_feedback(self):
        db.session.add(self)
        db.session.commit()



    def __init__(self,author,feedback):
        self.author = author
        self.feedback = feedback


class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(225),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_hash = db.Column(db.String(225))
    


    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)

    def __repr__(self):
        return f'User {self.username}'


class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")


    def __repr__(self):
        return f'User {self.name}'

app/models/pitch.py
class Pitch:
    '''
    Pitch class to define Pitch Objects
    '''

    def __init__(self,id,author,pitch,vote_average,vote_count):
        self.id =id
        self.author = author
        self.pitch = pitch
        self.vote_average = vote_average
        self.vote_count = vote_count

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required

class PitchForm(FlaskForm):
    category = SelectField('Pitch Category',choices=[('music','music'),
                                                        ('life','life'),
                                                        ('pickup','Pickup Pitch'),
                                                        ('interview','Interview Pitch'),
                                                        ('production','Production Pitch'),
                                                        ('promotion','Promotion Pitch')], validators=[Required()])
    author = StringField('Author', validators=[Required()])
    pitch = TextAreaField('Pitch', validators=[Required()])
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you',validators = [Required()])
    submit = SubmitField('Submit')

class FeedbackForm(FlaskForm):
    author = StringField('Author', validators=[Required()])
    feedback = TextAreaField('Feedback', validators=[Required()])
    submit= SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()

def create_app(config_name):

    app = Flask(__name__)

    #creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing Flask Extensions
    # bootstrap = Bootstrap(app)
    bootstrap.init_app(app)
    login_manager.init_app(app)
    db.init_app(app)
    mail.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    #configure UploadSet
    configure_uploads(app,photos)


    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from app.models import Pitches,Feedback
from flask_login import login_required,login_manager,current_user
from app.models import Pitches,User
from .forms import FeedbackForm,PitchForm,UpdateProfile
from .. import db,photos


@main.route('/',methods=['GET','POST'])
def index():

    '''
    View root page function that returns the index page and its data
    '''


    music=Pitches.query.filter_by(category='music').all()
    life=Pitches.query.filter_by(category='life').all()
    pickup=Pitches.query.filter_by(category='pickup').all()
    interview=Pitches.query.filter_by(category='interview').all()
    production=Pitches.query.filter_by(category='production').all()
    promotion=Pitches.query.filter_by(category='promotion').all()

    title = 'Home - One Minute Pitch'
    return render_template('index.html', title = title,life=life,music = music,pickup=pickup,interview=interview,production=production,promotion=promotion)

@main.route('/create/new', methods = ['GET','POST'])
@login_required
def create():
    '''
    View page that returns a form to create your own pitch
    '''
    form = PitchForm()
    if form.validate_on_submit():
        author = form.author.data
        category = form.category.data
        pitch = form.pitch.data
        new_pitch = Pitches(author=author,category=category,pitch=pitch)

        #save pitch method
        new_pitch.save_pitch()
        return redirect(url_for('main.index'))
    title = 'One Minute Pitch'
    music=Pitches.query.filter_by(category='music').all()
    return render_template('new_pitch.html',title=title,pitch_form=form)

@main.route('/feedback/new',methods= ['GET','POST'])
@login_required
def feedback():
    '''
    View page that returns a form to create your own feedback
    '''
    form = FeedbackForm()
    if form.validate_on_submit():
        author = form.author.data
        feedback= form.feedback.data
        new_feedback = Feedback(author=author,feedback= feedback)

        #save feedback methods
        new_feedback.save_feedback()
        return redirect(url_for('main.index'))
    title = 'One Minute Pitch'
    return render_template('new_feedback.html',title= title,feedback_form = form)

@main.route('/user/<uname>')
@login_required
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">



    {% include 'navbar.html' %}
    <hr>
    <br>
    {% block content%}

    {%endblock%}
    {% include 'footer.html' %}

app/templates/comment.html
{%extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf%}
{% import "macros.html" as macro %}
{% block content%}
  <div class="container">
    {{ wtf.quick_form(comment_form) }}

  </div>
{% endblock %}

app/templates/footer.html
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<style media="screen">
/* Style all font awesome icons */
.fa {
    padding: 20px;
    font-size: 30px;
    width: 50px;
    text-align: center;
    text-decoration: none;
}

/* Add a hover effect if you want */
.fa:hover {
  opacity: 0.7;
}

/* Set a specific color for each brand */

/* Facebook */
.fa-facebook {
  background: #3B5998;
  color: white;
}

/* Twitter */
.fa-twitter {
  background: #55ACEE;
  color: white;
}
.fa-snapchat{
  background: #ffff66;
  color: white;
}
</style>


<footer class="page-footer center-on-small-only mdb-color lighten-3">

    <!--Footer Links-->
    <div class="container">
        <div class="row my-4">

            <!--First column-->
            <div class="col-md-4 col-lg-4">
                <h5 class="title mb-4 font-bold">About</h5>
                <p>Its a website where users can view diffrent pitches in diffrent categories <br> Users can also create their own pich and post it for other users to view.</p>
            </div>
            <!--/.First column-->

            <hr class="clearfix w-100 d-md-none">

            <!--Second column-->
            <!-- <div class="col-md-2 col-lg-2 ml-auto">
                <h5 class="title mb-4 font-bold">About</h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            </div> -->
            <!--/.Second column-->

            <hr class="clearfix w-100 d-md-none">

            <!--Third column-->
            <div class="col-md-4 col-lg-3">
                <h5 class="title mb-4 font-bold">Contact</h5>
                <!--Info-->
                <p><i class="fa fa-home mr-3"></i> One Minute Pitch, Nairobi</p>
                <p><i class="fa fa-envelope mr-3"></i> oneminute@pitch.com</p>
                <p><i class="fa fa-phone mr-3"></i> +254712345671 </p>
            </div>
            <!--/.Third column-->

            <hr class="clearfix w-100 d-md-none">

            <!--Fourth column-->
            <div class="col-md-2 col-lg-2 text-center">
                <h5 class="title mb-4 font-bold">Follow Us</h5>
                <!--Social buttons-->
                <div class="social-section mt-2 ">
                    <!--Facebook-->
                    <a href="https://www.facebook.com/jah.guevarapalmer" class="fa fa-facebook"></a>
                    <!--Twitter-->
                    <a href="https://twitter.com/VincentMuya" class="fa fa-twitter"></a>
                    <a href="#" class="fa fa-snapchat"></a>
                </div>
            </div>
            <!--/.Fourth column-->

        </div>
    </div>
    <!--/.Footer Links-->

    <!--Copyright-->
    <div class="footer-copyright">
        <div class="container-fluid">
            © 2018 Copyright:

        </div>
    </div>
    <!--/.Copyright-->

</footer>

app/templates/fourOwfour.html
{% extends 'base.html'%}

{%block content%}
<h1>Sorry the page can be found</h1>
{%endblock%}

app/templates/index.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf%}
{% import 'macros.html' as macro%}

{% block content%}
<h5><em>Click To Create a Pitch</em></h5>
<button type="button" name="button"><a href="/create/new">Create a Pitch</a></button>

<div class="container">

  <div class="tabs">
     <div class="row">
       <div class="col-md-2">
        <h4>Category</h4>
       <h5>Pickup</h5>
     </div>
   <ul id="pickup">
  {{macro.displayPitchList(pickup)}}
  </ul>
      <div class="col-md-10">
    </div>
  </div>
  </div>
<hr>
<br>
  <div class="tabs">
     <div class="row">
       <div class="col-md-2">
         <h4>Category</h4>
       <h5>life</h5>
     </div>
     <ul id="life">
  {{macro.displayPitchList(life)}}
  </ul>
  <div class="col-md-10">
  </div>
  </div>
  </div>
<hr>
<br>
<div class="tabs">
   <div class="row">
     <div class="col-md-2">
      <h4>Category</h4>
     <h5>Music</h5>
   </div>
 <ul id="music">
{{macro.displayPitchList(music)}}
</ul>
    <div class="col-md-10">
  </div>
</div>
</div>
<hr>
<br>
<div class="tabs">
   <div class="row">
     <div class="col-md-2">
      <h4>Category</h4>
     <h5>Interview</h5>
   </div>
 <ul id="interview">
{{macro.displayPitchList(interview)}}
</ul>
    <div class="col-md-10">
  </div>
</div>
</div>
<hr>
<br>
<div class="tabs">
   <div class="row">
     <div class="col-md-2">
      <h4>Category</h4>
     <h5>Promotion</h5>
   </div>
 <ul id="promotion">
{{macro.displayPitchList(promotion)}}
</ul>
    <div class="col-md-10">
  </div>
</div>
</div>
<hr>
<br>
<div class="tabs">
   <div class="row">
     <div class="col-md-2">
      <h4>Category</h4>
     <h5>Production</h5>
   </div>
 <ul id="production">
{{macro.displayPitchList(production)}}
</ul>
    <div class="col-md-10">
  </div>
</div>
</div>
<hr>
<br>
<button type="button" name="button"><a href="/feedback/new">Give one Minute Pitch a Feedback or Surgestion</a></button>

</div>
{%endblock%}

app/templates/macros.html
{% macro displayPitchList(pitch_list) %}

  {% for pitch in pitch_list %}
  <li>Author:{{pitch.author}}</li>
  <li>Pitch:{{pitch.pitch}}</li>
  {% endfor %}
  {% endmacro %}

app/templates/navbar.html
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

</head>

<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#"><strong><em>One Minute Pitch<em></strong></a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/#pickup">PickUp Pitches</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/#music">Music Pitches</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/#life">Life Pitches</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="/#interview">Interview Pitches</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="/#production">Production Pitches</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="/#promotion">Promotion Pitches</a>
      </li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
     {% if current_user.is_authenticated %}
     <li>{{current_user.username}}</li>
   <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
   <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
   {% else %}
   <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
   {%endif%}
     </ul>
  </div>
</nav>

app/templates/new_feedback.html
{%extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf%}
{% import "macros.html" as macro %}
{% block content%}
  <div class="container">
    {{ wtf.quick_form(feedback_form) }}

  </div>
{% endblock %}

app/templates/new_pitch.html
{%extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf%}
{% import "macros.html" as macro %}
{% block content%}
  <div class="container">
    {{ wtf.quick_form(pitch_form) }}


    <div class="row">

         <h1>Pitches</h1>
         <hr>

         <!-- {% if new_pitches %}
             {{macro.displayPitchList(inspiration)}}
         {% endif %} -->

     </div>
  </div>
{% endblock %}

app/templates/pitch.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}

div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 movie-details">
            <h3>{{ pitch.author }}</h3>

            <p class="overview"> {{ pitch.overview }}</p>

            <p class="ratings"> <i>{{ pitch.vote_count}} votes </i> </p>
            <a class="ratings" href="/pitch/pitch/new/{{pitch.id}}"> Write a New Pitch</a>

</div>

{% endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}

    {% if user == current_user %}
     <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
   {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}

    {% if user == current_user%}
    <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file" name="photo" class="form-control" required>
      <input type="submit">
      {%endif%}
      
  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
  {{wtf.quick_form(form)}}
{% endblock %}